CREATE TABLE public.applications (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NULL DEFAULT now(),
  phone_number text NOT NULL,
  full_name text NOT NULL,
  dob date NULL,
  gender text NULL,
  city text NULL,
  locality text NULL,
  documents jsonb NULL,
  status text NULL,
  CONSTRAINT applications_pkey PRIMARY KEY (id)
);