import { WorkerCategory, ServiceType } from '../types';

export const SERVICES_BY_CATEGORY: Record<WorkerCategory, ServiceType[]> = {
    [WorkerCategory.PLUMBER]: [
        { id: 'plumb-1', name: 'Leak Repair', description: 'Fixing leaking pipes or taps', price: 500, duration: '1 hr' },
        { id: 'plumb-2', name: 'Tap Installation', description: 'Install new taps or faucets', price: 300, duration: '30 mins' },
        { id: 'plumb-3', name: 'Drain Cleaning', description: 'Unclogging blocked drains', price: 800, duration: '1.5 hrs' },
        { id: 'plumb-4', name: 'General Plumbing', description: 'General inspection and minor repairs', price: 600, duration: '1 hr' },
    ],
    [WorkerCategory.ELECTRICIAN]: [
        { id: 'elec-1', name: 'Fan Installation', description: 'Install ceiling or wall fans', price: 400, duration: '45 mins' },
        { id: 'elec-2', name: 'Switch Repair', description: 'Fix faulty switches or sockets', price: 200, duration: '30 mins' },
        { id: 'elec-3', name: 'Wiring Check', description: 'Full house wiring inspection', price: 1000, duration: '2 hrs' },
    ],
    [WorkerCategory.MAID]: [
        { id: 'maid-1', name: 'House Cleaning', description: 'General house cleaning', price: 400, duration: '1 hr' },
        { id: 'maid-2', name: 'Dish Washing', description: 'Washing dishes and utensils', price: 300, duration: '45 mins' },
    ],
    [WorkerCategory.CARPENTER]: [
        { id: 'carp-1', name: 'Furniture Repair', description: 'Fixing broken furniture', price: 600, duration: '1 hr' },
        { id: 'carp-2', name: 'Door Lock Repair', description: 'Repairing or replacing door locks', price: 400, duration: '45 mins' },
    ],
    [WorkerCategory.PAINTER]: [
        { id: 'paint-1', name: 'Wall Painting', description: 'Painting a single wall', price: 1500, duration: '4 hrs' },
    ],
    [WorkerCategory.GARDENER]: [
        { id: 'gard-1', name: 'Lawn Mowing', description: 'Mowing and trimming the lawn', price: 500, duration: '1 hr' },
    ],
    [WorkerCategory.HOUSE_CLEANING]: [
        { id: 'clean-1', name: 'Deep Cleaning', description: 'Full deep cleaning of the house', price: 2000, duration: '4 hrs' },
    ],
    [WorkerCategory.LAUNDRY_SERVICE]: [],
    [WorkerCategory.PEST_CONTROL]: [],
    [WorkerCategory.APPLIANCE_REPAIR]: [],
    [WorkerCategory.LOCKSMITH]: [],
    [WorkerCategory.PACKERS_AND_MOVERS]: [],
    [WorkerCategory.MECHANIC]: [],
    [WorkerCategory.CAR_WASHING]: [],
    [WorkerCategory.DRIVER]: [],
    [WorkerCategory.BIKE_REPAIR]: [],
    [WorkerCategory.ROADSIDE_ASSISTANCE]: [],
    [WorkerCategory.TUTOR]: [],
    [WorkerCategory.FITNESS_TRAINER]: [],
    [WorkerCategory.DOCTOR_NURSE]: [],
    [WorkerCategory.TIFFIN_SERVICE]: [],
    [WorkerCategory.BEAUTICIAN]: [],
    [WorkerCategory.BABYSITTER]: [],
    [WorkerCategory.PET_SITTER]: [],
    [WorkerCategory.COOK]: [],
    [WorkerCategory.ERRAND_RUNNER]: [],
    [WorkerCategory.DOCUMENTATION_ASSISTANCE]: [],
    [WorkerCategory.TECH_SUPPORT]: [],
    [WorkerCategory.PHOTOGRAPHY]: [],
    [WorkerCategory.VIDEOGRAPHY]: [],
    [WorkerCategory.SECURITY]: [],
    [WorkerCategory.CATERING]: [],
    [WorkerCategory.DIGITAL_MARKETING]: [],
    [WorkerCategory.CONTENT_CREATIVE]: [],
    [WorkerCategory.TECH_DEV]: [],
    [WorkerCategory.BUSINESS_OPS]: [],
    [WorkerCategory.KNOWLEDGE_SERVICES]: [],
    [WorkerCategory.PROFESSIONAL_ADVISORY]: [],
    [WorkerCategory.WELLNESS_ONLINE]: [],
    [WorkerCategory.CREATOR_ECONOMY]: [],
    [WorkerCategory.LOCAL_BIZ_DIGITIZATION]: [],
    [WorkerCategory.OTHER]: [],
};
